version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-2"
    REACT_APP_SERVER_URL: "http://flask-react-alb-471021971.us-east-1.elb.amazonaws.com"
    username: "adihusky"
    password: "adi6DOCKER@"
       
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
          -f backend/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uberbusapp-be:prod \
          ./be
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:prod
    - printf '[{"name":"uberapp-be-td","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/uberbusapp-be:prod > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
    
